[package]
name = "FileIndex"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.9"
log = "0.4"
env_logger = "0.11"
tokio = { version = "1.47", features = ["default", "rt-multi-thread", "full"] }